In [1]:
import tensorflow as tf

In [2]:
hello = tf.constant('Hello,Tensorflow!')
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [3]:
hello = tf.constant('hello,tensorflow!')
print(hello)

Tensor("Const_1:0", shape=(), dtype=string)


In [4]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b)

In [5]:
sess = tf.Session()
print (sess.run(hello))
print(sess.run([a,b,c,]))
sess.close()

b'hello,tensorflow!'
[10, 32, 42]


In [6]:
X = tf.placeholder(tf.float32,[None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [7]:
X = tf.placeholder(tf.float32,[None,3])

In [8]:
X_data = [[1,2,3],[4,5,6]]

In [10]:
import numpy as np
X_data = np.array(X_data)
X_data.shape

(2, 3)

In [12]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [13]:
W = tf.Variable([[0.1,0.1],[0.2,0.2],[0.3,0.3]])

In [14]:
expr = tf.matmul(X,W)+b

In [15]:
expr.shape

TensorShape([Dimension(2), Dimension(2)])

In [22]:
sess  = tf.Session()
sess.run(tf.global_variables_initializer())

print(X_data)
print(sess.run(W))
print(sess.run(b))
print(sess.run(expr,feed_dict = {X:X_data}))

[[1 2 3]
 [4 5 6]]
[[ 0.1         0.1       ]
 [ 0.2         0.2       ]
 [ 0.30000001  0.30000001]]
[[ 0.03646772]
 [-0.25234243]]
[[ 1.43646777  1.43646777]
 [ 2.94765759  2.94765759]]


In [23]:
x_data = [1,2,3]
y_data = [1,2,3]

In [25]:
W  =tf.Variable(tf.random_uniform([1],-1.0,1.0))
b = tf.Variable(tf.random_uniform([1],-1.0,1.0))

In [26]:
X = tf.placeholder(tf.float32,name = 'X')
Y = tf.placeholder(tf.float32,name = 'Y')

In [27]:
print(X)

Tensor("X:0", dtype=float32)


In [28]:
n = tf.placeholder(tf.float32)

In [29]:
print(n)

Tensor("Placeholder_2:0", dtype=float32)


In [30]:
hypothesis = W*X+b

In [31]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [32]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1)
train_op = optimizer.minimize(cost)

In [37]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _,cost_val = sess.run([train_op,cost],feed_dict = {X:x_data,Y:y_data})
        
        print(step,cost_val,sess.run(W),sess.run(b))
        
        
    print(sess.run(hypothesis, feed_dict = {X:5}))
    print(sess.run(hypothesis, feed_dict = {X:3}))

0 1.80081 [ 1.32384276] [-0.58392429]
1 0.0739816 [ 1.25515926] [-0.59667653]
2 0.0508619 [ 1.25568128] [-0.57940489]
3 0.0482117 [ 1.24880731] [-0.56579643]
4 0.0459188 [ 1.24290574] [-0.55216008]
5 0.0437376 [ 1.23705769] [-0.53889036]
6 0.04166 [ 1.23135996] [-0.52593535]
7 0.0396811 [ 1.22579813] [-0.51329225]
8 0.0377963 [ 1.22037017] [-0.50095302]
9 0.0360009 [ 1.21507251] [-0.4889105]
10 0.0342908 [ 1.20990241] [-0.47715741]
11 0.032662 [ 1.2048564] [-0.46568692]
12 0.0311105 [ 1.19993186] [-0.45449209]
13 0.0296328 [ 1.19512558] [-0.44356641]
14 0.0282252 [ 1.19043493] [-0.43290335]
15 0.0268845 [ 1.18585694] [-0.42249665]
16 0.0256074 [ 1.18138909] [-0.4123401]
17 0.024391 [ 1.17702866] [-0.4024277]
18 0.0232325 [ 1.172773] [-0.39275363]
19 0.0221289 [ 1.16861963] [-0.38331211]
20 0.0210778 [ 1.16456616] [-0.37409753]
21 0.0200766 [ 1.16061008] [-0.3651045]
22 0.0191229 [ 1.15674913] [-0.35632762]
23 0.0182145 [ 1.15298104] [-0.34776175]
24 0.0173493 [ 1.14930344] [-0.33940181

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_data = np.array(
    [[0,0],[1,0],[1,1],[0,0],[0,0],[0,1]])

In [3]:
y_data = np.array([
    [1.,0.,0.],
    [0.,1.,0.],
    [0.,0.,1.],
    [1.,0.,0.],
    [1.,0.,0.],
    [0.,0.,1.]
])

In [4]:
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [5]:
W = tf.Variable(tf.random_uniform([2,3],-1.,1.))
b = tf.Variable(tf.zeros([3]))

In [6]:
L = tf.add(tf.matmul(X,W),b)
L = tf.nn.relu(L)
model = tf.nn.softmax(L)

In [7]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(W))
    print(sess.run(b))

[[ 0.38281083  0.59908772 -0.35579467]
 [-0.63628459  0.0378077   0.12279105]]
[ 0.  0.  0.]


In [8]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(model),axis = 1))

In [9]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train_op = optimizer.minimize(cost)

In [10]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(100):
        _,cost_val = sess.run([train_op,cost],feed_dict={X:x_data,Y:y_data})
        
        if (step+1) % 10 == 0:
            print(step+1,cost_val)

10 1.14458
20 1.13395
30 1.12381
40 1.11401
50 1.10469
60 1.09577
70 1.08717
80 1.07976
90 1.07413
100 1.06867


In [11]:
prediction = tf.argmax(model,axis = 1)
target = tf.argmax(Y,axis = 1)

In [12]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('actual:',sess.run(target,feed_dict = {Y: y_data}))
    print('estimated:',sess.run(prediction,feed_dict = {X:x_data}))
    

    is_correct = tf.equal(prediction,target)
    accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))
    print('accuracy:%2f' % sess.run(accuracy*100,feed_dict = {X:x_data,Y:y_data}))
    

actual: [0 1 2 0 0 2]
estimated: [0 2 2 0 0 0]
accuracy:66.666672
