In [6]:
import tensorflow as tf
import matplotlib.pyplot as plt

X = tf.placeholder(tf.float32,[None,3])
print(X)

Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)


In [2]:
x_data = [[1,2,3],[4,5,6]]

In [4]:
W = tf.Variable(tf.random_normal([3,2]))

In [10]:
b = tf.Variable(tf.random_normal([2,1]))

In [11]:
expr = tf.matmul(X,W) + b
sess = tf.Session()

In [12]:
sess.run(tf.global_variables_initializer())

In [13]:
print('x_data')

x_data


In [14]:
print(x_data)

[[1, 2, 3], [4, 5, 6]]


In [15]:
print('W')

W


In [16]:
print(sess.run(W))

[[ 2.07320166 -0.83878201]
 [-0.7578209  -0.54421985]
 [ 1.07625246  1.24438727]]


In [17]:
plt(sess.run(W))

TypeError: 'module' object is not callable

In [18]:
print('b')

b


In [19]:
print(sess.run(b))

[[-0.72095656]
 [ 1.20524299]]


In [20]:
print('expr')

expr


In [22]:
print(sess.run(expr,feed_dict={X:x_data}))

[[  3.06536078   1.08498359]
 [ 12.16646004   2.59533978]]


In [23]:
sess.close()