In [1]:
import tensorflow as tf

In [2]:
x = tf.placeholder(tf.float32,[None,3])

In [3]:
print(x)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [4]:
input = [[1,2,3],[4,5,6]]

In [6]:
w = tf.Variable(tf.random_normal([3,2]))

In [8]:
b = tf.Variable(tf.random_normal([2,1]))

In [9]:
hypothesis = tf.matmul(x,w)+b

In [10]:
sess=tf.Session()

In [11]:
sess.run(tf.global_variables_initializer())

In [12]:
print('--input--')

--input--


In [13]:
print(input)

[[1, 2, 3], [4, 5, 6]]


In [14]:
print('--w--')

--w--


In [15]:
print(sess.run(w))

[[ 0.19812542  2.06908369]
 [ 1.03356981  0.57582104]
 [ 1.11484742  0.32269698]]


In [16]:
print('--b--')

--b--


In [17]:
print(sess.run(b))

[[-1.46015644]
 [-0.32966477]]


In [18]:
print('--hypothesis--')

--hypothesis--


In [19]:
print(sess.run(hypothesis,feed_dict={x:input}))

[[  4.14965057   2.72866011]
 [ 12.31976986  12.76195621]]


In [20]:
sess.close()

In [21]:
import tensorflow as tf
a = tf.placeholder(tf.float32,[None,None])

In [22]:
I = tf.placeholder(tf.float32,[2,4])

In [23]:
i=[[1,2,3,4],[5,6,7,8]]

In [24]:
W = tf.placeholder(tf.float32,[4,2])

In [25]:
w = [[1,1],[2,2],[3,3],[4,4]]

In [26]:
node = tf.matmul(I,W)

In [27]:
sess = tf.Session()

In [28]:
sess.run(tf.global_variables_initializer())

In [29]:
print(sess.run(node,feed_dict={I:i,W:w}))

[[ 30.  30.]
 [ 70.  70.]]


In [30]:
sess.close()

In [31]:
x = tf.constant(10)

In [32]:
y = tf.constant(5)

In [33]:
c = tf.add(x,y)

In [34]:
sess = tf.Session()

In [35]:
print(sess.run(c))

15


In [36]:
sess.close()