In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt

X = tf.placeholder(tf.float32,[None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [2]:
x_data = [[1,2,3],[4,5,6]]

In [4]:
W = tf.Variable(tf.random_normal([3,2]))

In [10]:
b = tf.Variable(tf.random_normal([2,1]))

In [11]:
expr = tf.matmul(X,W) + b
sess = tf.Session()

In [12]:
sess.run(tf.global_variables_initializer())

In [13]:
print('x_data')

x_data


In [14]:
print(x_data)

[[1, 2, 3], [4, 5, 6]]


In [15]:
print('W')

W


In [16]:
print(sess.run(W))

[[ 2.07320166 -0.83878201]
 [-0.7578209  -0.54421985]
 [ 1.07625246  1.24438727]]


In [17]:
plt(sess.run(W))

TypeError: 'module' object is not callable

In [18]:
print('b')

b


In [19]:
print(sess.run(b))

[[-0.72095656]
 [ 1.20524299]]


In [20]:
print('expr')

expr


In [22]:
print(sess.run(expr,feed_dict={X:x_data}))

[[  3.06536078   1.08498359]
 [ 12.16646004   2.59533978]]


In [23]:
sess.close()

In [3]:
hello =  tf.constant('hello,tensorflow!')

In [4]:
#start a TF session

In [5]:
sess =tf.Session()

In [6]:
print(sess.run(hello))

b'hello,tensorflow!'


In [3]:
node1 = tf.constant(3.0,tf.float32)
node2 = tf.constant(4.0) # tf.float32 implicitly
node3 = tf.add(node1,node2)

In [4]:
print('node1:',node1,'node2:',node2)
print('node3:',node3)

node1: Tensor("Const:0", shape=(), dtype=float32) node2: Tensor("Const_1:0", shape=(), dtype=float32)
node3: Tensor("Add:0", shape=(), dtype=float32)


In [5]:
sess = tf.Session()
print('sess.run(node1,node2):',sess.run([node1,node2]))

sess.run(node1,node2): [3.0, 4.0]


In [6]:
print('sess.run(node3):',sess.run(node3))

sess.run(node3): 7.0


In [8]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b
print(sess.run(adder_node,feed_dict={a:3,b:4.5}))
print(sess.run(adder_node,feed_dict={a:[1,3],b:[2,4]}))

7.5
[ 3.  7.]


In [9]:
[1.,2.,3.]

[1.0, 2.0, 3.0]

In [10]:
[[1.,2.,3.],[4.,5.,6.]]

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [11]:
[[[1.,2.,3.]],[[7.,8.,9.]]]

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

In [12]:
t = tf.constant([1.,2.,3.])

In [13]:
t= tf.Constant([1.,2.,3.])

AttributeError: module 'tensorflow' has no attribute 'Constant'